Portfolio: accessibility
nilab-khwaja/My_Portfolio pull request #10
Opened 2023-03-07 15:13 UTC by tGemechis7

> Pages title -- there is no issue found 
> Image text alternative -- the issue was found we put the  link down below 
> Text headings-- there is no issue found
> color contrast--- there is no issue found
> Resize ----there is no issue found
> interaction------there is no found
> moving content---- there is no issue found
> Multimedia----- there is no issue found
> The basic structure of the page--- there no issue found

The link we put down which needed to changes
https://github.com/nilab-khwaja/My_Portfolio/blob/33f119243fe243c7c1e1bf2a5f37c40a914c31b5/index.html#L32-L33
https://github.com/nilab-khwaja/My_Portfolio/blob/33f119243fe243c7c1e1bf2a5f37c40a914c31b5/index.html#L46
https://github.com/nilab-khwaja/My_Portfolio/blob/33f119243fe243c7c1e1bf2a5f37c40a914c31b5/index.html#L250
https://github.com/nilab-khwaja/My_Portfolio/blob/33f119243fe243c7c1e1bf2a5f37c40a914c31b5/index.html#L261
https://github.com/nilab-khwaja/My_Portfolio/blob/33f119243fe243c7c1e1bf2a5f37c40a914c31b5/index.html#L266-L274
https://github.com/nilab-khwaja/My_Portfolio/blob/33f119243fe243c7c1e1bf2a5f37c40a914c31b5/index.html#L282
https://github.com/nilab-khwaja/My_Portfolio/blob/33f119243fe243c7c1e1bf2a5f37c40a914c31b5/index.html#L287

2023-03-07 15:58 UTC, Abenezer-Tilahun requested changes
Hi @tGemechis7 @nilab-khwaja   , 

Great job for implemented  the suggested changes , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ No Linters error
✔️ You used correct Git Hub-Flow.
✔️ Good commit messages
✔️ Professional READEME 


![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

- [x] For the Heading part Kindly makes sure that Heading levels  have a meaningful hierarchy, The heading hierarchy is meaningful. Ideally, the page starts with an "h1" — which is usually similar to the page title — and does not skip levels;For also the purpose of search and optimization it 's better to have one h1 heading but I see that you have two h1 heading, Kindly fix it. 
![Capture](https://user-images.githubusercontent.com/93598189/223475833-1edf19ab-2e3a-4455-845e-1d44526789d0.PNG)

- [ ] For the Contrast ratio ("color contrast"):there is some issues for the button's contrast of this page, Kindly use[this aditus tool](https://www.aditus.io/button-contrast-checker/) to help to check the color contrast of the project.


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-07 15:58 UTC, Abenezer-Tilahun commented on index.html
> +    <title>My-Portfolio </title>
- [ ] For the page titles Kindly make sure that It adequately and briefly describes the content of the page. For example:

- Poor titles:

```
Microverse project | Your portfolio.
Portifolio project | My-Portfolio
```

- Better page titles:

```
Mark's portifolio
Mark full-stack webdeveloper
```

2023-03-07 19:01 UTC, nilab-khwaja commented on index.html
> +    <title>My-Portfolio </title>
Hi   @Abenezer-Tilahun 
Could you please tell me how to use solve contrast issues , Because we just used Figma templet .We need more detail please.

2023-03-08 11:11 UTC, DuaneDave approved these changes
Hi @nilab-khwaja 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Button contrast improved
✔️ Header ranking correct according to siteimprove acessibility checker
✔️ Meaningful page title

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-08 11:20 UTC, merged